name: flutter_checkdoc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.8
  dio: ^5.4.2+1
  meta: ^1.11.0
  flutter_dropzone: ^4.0.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/dotenv
  - assets/images/
  - assets/

fonts:
  - family: MaterialIcons
    fonts:
      - asset: assets/fonts/MaterialIcons-Regular.otf
